name: Veille quotidienne
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  veille:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installation des dépendances
        run: pip install requests
      - name: Lancement de la veille
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
        run: python veille.py
