name: Veille quotidienne
on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 13 * * *"
  workflow_dispatch:
jobs:
  veille:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installation des dépendances
        run: pip install requests feedparser beautifulsoup4
      - name: Lancement de la veille
        env:
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python veille.py
